config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destory]
  root  'static_pages#home'
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/auth/:provider/callback', to: 'tumblrs#callback', via: 'get'
  match '/tag', to: 'tumblrs#tag', via: 'post'
  match '/search', to: 'tumblrs#search', via: 'post'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false}
  has_secure_password
  validates :password, length: { minimum: 6 }

def User.new_remember_token
  SecureRandom.urlsafe_base64
end

def User.encrypt(token)
  Digest::SHA1.hexdigest(token.to_s)
end


def self.prepare_access_token(user)
  consumer = OAuth::Consumer.new("API key", "API secret",{:site => "http://www.tumblr.com/"})
  token_hash = {:oauth_token => user.token,:oauth_token_secret => user.secret}
  access_token = OAuth::AccessToken.from_hash(consumer, token_hash )
end


private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/tumblrs_controller.rb
#coding: utf-8
class TumblrsController < ApplicationController
  #include tumblr_request

    def callback 
      session['tumblr_session'] = Tumblr::App::Auth.authenticate(request.env["omniauth.auth"])
      config = TUMBLR_OAUTH_REDIRECT
      redirect_to "/"
    end

    #検索
    def search
      tag_search
    end


    def tag_search
        #TODO:module化
        #response = tag(params[:keyword])
        uri = URI.parse(URI.escape("http://api.tumblr.com/v2/tagged?tag=#{params[:keyword]}&api_key=#{Settings.tumblr.api_key}"))

        @items = MultiJson.load(Net::HTTP.get(uri), :symbolize_keys => true)[:response]

        #logger.debug(@items)

        #responseの中身確認
        #@items.each do |item|
          #logger.debug(item["blog_name"])
        #end

        #情報詰め替え
        #@tags = hoge items
        #logger.debug(@tags).inspect
    end

    #TODO:名前を決める
    #TODO:module?に移動
    #TODO:写真表示用共通の処理にする
    def hoge(items)
      result = Hash.new
      #詰め替え
      items.each do |item| 
        result = {:tags => item["tags"]} if item["tags"]
        logger.debug("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")

        if item["photos"] 
          photo = {}
          item["photos"].each do |photo|
            photo["alt_sizes"].each do |alt| 
              photo = {:width => photo["width"]} if item["width"]
              photo = {:height => photo["height"]} if item["height"]
              photo = {:url => photo["url"]} if item["url"]
            end
            result = {:photos => photo}
          end
        end 
      end
      return result
    end 

    #def create
        #raise request.env["omniauth.auth"].to_yaml  
        #auth = request.env["omniauth.auth"]

        # Twitter.configure do |config|
        # config.consumer_key = 'CONSUMER_KEY'
        # config.consumer_secret = 'CONSUMER_SECRET'
        # config.oauth_token = auth['credentials']['token']
        # config.oauth_token_secret = auth['credentials']['secret']
        # end
    
        # resirect_to リダイレクト先のURL :notice => 'sign in'
    #end




  # def index
  #   if request.get?
  #   else
  #     @keyword = params[:keyword]
  #     res = Amazon::Ecs.item_search(@keyword, {
  #       :search_index => 'Music',
  #       :response_group => 'Medium',
  #       :sort => 'salesrank'
  #     })
  #     @items = []
  #     res.items.each do |item|
  #       @items << Item.new(
  #         item.get('asin'),
  #         item.get('itemattributes/title'),
  #         item.get('detailpageurl'),
  #         item.get_hash('smallimage')
  #       )
  #     end
  #   end
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy] #sign inしているか
  before_action :correct_user, only: [:edit, :update] #ログインユーザか
  before_action :admin_user, only: [:destroy] #adminユーザか

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    #@user = User.find(params[:id])
  end


  def update
    #@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user

    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end




  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


    # Before actions

    def signed_in_user
      unless signed_in?
        store_location
        flash[:notice] = "Please sign in." 
        redirect_to signin_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        redirect_to(root_path)
      end
    end

    def admin_user
      unless current_user.admin?
        redirect_to(root_path)
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
  #ページ毎のタイトルを返す
  def full_title(page_title)
    base_title = "Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    sign_out
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  #フレンドリーフォワーディング
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tumblrs_helper.rb
module TumblrsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.jp/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.jp/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <div class="navbar">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 left-nav">
          <a class="w-inline-block" href="index.html">
            <img class="logo" src="images/space-logo.svg" width="37" alt="52f175d20128ab830c0001c0_space-logo.svg">
            <div class="brand">Taglr</div>
          </a>
        </div>
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 right-nav">
          <a class="w-inline-block social-btn" href="http://facebook.com/webflow">
            <img src="images/facebook-icon_black.svg" width="25" alt="52f158327711748d2600072b_facebook-icon_black.svg">
          </a>
          <a class="w-inline-block social-btn" href="http://twitter.com/webflowapp">
            <img src="images/twitter-icon_black.svg" width="25" alt="52f158467711748d2600072c_twitter-icon_black.svg">
          </a>
        </div>
      </div>
    </div>
  </div>

  <% if false %>  
  <div class="navbar">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 left-nav">
          <a class="w-inline-block" href="/">
            <img class="logo" src="images/space-logo.svg" width="37" alt="52f175d20128ab830c0001c0_space-logo.svg">
            <div class="brand">Taglr</div>
          </a>
        </div>
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 right-nav">
          <%= link_to "Home",    root_path %>
          <%= link_to "Help",    help_path %>
              <% if signed_in? %>
                <%= link_to "Users", users_path %>
                <%= link_to "Profile", current_user %>
                <%= link_to "Settings", edit_user_path(current_user) %>
                 <%= link_to "Sign out", signout_path, method: "delete" %>
              <% else %>
                <%= link_to "Sign in", signin_path %>
              <% end %>
          <a class="w-inline-block social-btn" href="http://facebook.com/webflow">
            <img src="images/facebook-icon_black.svg" width="25" alt="52f158327711748d2600072b_facebook-icon_black.svg">
          </a>
          <a class="w-inline-block social-btn" href="http://twitter.com/webflowapp">
            <img src="images/twitter-icon_black.svg" width="25" alt="52f158467711748d2600072c_twitter-icon_black.svg">
          </a>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <% if false %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Help",    help_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                  <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", signout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
  <% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Webflow">
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
      <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
      <script>
        WebFont.load({
          google: {
            families: ["Roboto:300,regular","Roboto Condensed:regular"]
          }
        });
      </script>

    <%= render 'layouts/shim' %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
      <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  </head>

  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>


<% if false %>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>
    This is the home page for the
      <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/home.html.erb
  
  <div class="section hero">
    <div class="w-container container">
      <h1>Taglr</h1>
      <div class="w-form sign-up-form">
        <%= form_tag("/search", action: "search") do %>
          <%= text_field_tag :keyword %>
          <%= submit_tag "検索" %>
        <% end %>
        <div class="w-form-done success-message">
          <p>Thanks! You'll be the first to know.</p>
          <p class="spread-word">Help spread the word!</p>
          <div class="w-clearfix social-widget-wrapper">
            <div class="w-widget w-widget-twitter social-widget">
              <iframe src="https://platform.twitter.com/widgets/tweet_button.html#url=http%3A%2F%2Fwebflow.com&amp;counturl=webflow.com&amp;text=Check%20out%20this%20site&amp;count=horizontal&amp;size=m&amp;dnt=true" scrolling="no" frameborder="0" allowtransparency="true"
              style="border: none; overflow: hidden; width: 110px; height: 20px;"></iframe>
            </div>
            <div class="w-widget w-widget-facebook social-widget">
              <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Ffacebook.com%2Fwebflow&amp;layout=button_count&amp;locale=en_US&amp;action=like&amp;show_faces=false&amp;share=false" scrolling="no" frameborder="0" allowtransparency="true"
              style="border: none; overflow: hidden; width: 90px; height: 20px;"></iframe>
            </div>
          </div>
        </div>
        <div class="w-form-fail error-message">
          <p>Oops! Something went wrong while submitting the form. :(</p>
        </div>
      </div>
    </div>
  </div>
  <div class="social-section">
    <div class="w-container">
      <h2>Tell your friends.</h2>
      <p>Want more unlimited storage? Refer more friends.</p>
      <div class="share-wrapper">
        <div class="w-widget w-widget-facebook share-btn">
          <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Ffacebook.com%2Fwebflow&amp;layout=box_count&amp;locale=en_US&amp;action=like&amp;show_faces=false&amp;share=false" scrolling="no" frameborder="0" allowtransparency="true" style="border: none; overflow: hidden; width: 55px; height: 65px;"></iframe>
        </div>
        <div class="w-widget w-widget-twitter share-btn">
          <iframe src="https://platform.twitter.com/widgets/tweet_button.html#url=http%3A%2F%2Fwebflow.com&amp;counturl=webflow.com&amp;text=Check%20out%20this%20site&amp;count=vertical&amp;size=m&amp;dnt=true" scrolling="no" frameborder="0" allowtransparency="true"
          style="border: none; overflow: hidden; width: 55px; height: 62px;"></iframe>
        </div>
        <div class="w-widget w-widget-gplus share-btn">
          <div class="g-plusone" data-href="http://webflow.com" data-size="tall" data-annotation="bubble" data-width="120" data-recommendations="false" id="___plusone_0" style="width: 50px; height: 60px; text-indent: 0px; margin: 0px; padding: 0px; border-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; display: inline-block; background: transparent;"></div>
        </div>
      </div>
    </div>
  </div>

<% if false %>
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

<li><%= link_to "Tumblr", '/auth/tumblr' %></li>

    <%= form_tag("/search", action: "search") do %>
      <%= text_field_tag :keyword %>
      <%= submit_tag "検索" %>
    <% end %>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

<% end %>

app/views/tumblrs/search.html.erb
<p>検索結果</p>
<% if @items && @items.size > 0 %>
<table>
  <% @items.each do |item| %>

  <% if item[:type] == "photo" %>
      <% logger.debug(item) %>
    <% if item[:blog_name] %>
      <tr><td>Title: <%= item[:blog_name] %></td></tr>
    <% end %>

    <tr>

      <% if item[:photos] %>
        <% item[:photos][0][:alt_sizes].size.times { |i| %>
            <% if item[:photos][0][:alt_sizes][i][:width] == 500 %>
              <tr>
              <td><%= link_to(image_tag(item[:photos][0][:alt_sizes][i][:url], :size => "#{item[:photos][0][:alt_sizes][i][:width]}x#{item[:photos][0][:alt_sizes][i][:height]}", :alt => item[:photos][0][:alt_sizes][i][:title]), item[:photos][0][:alt_sizes][i][:url], :target => '_blank') %></td>
              </tr>
            <% end %>
        <% } %>
      <% end %>




      <% if item[:tags] %>
        <tr>
        <td>Tags:</td>
        <% item[:tags].each do |tag| %>
          <td><%= tag %></td>
        <% end %>
        </tr>
      <% end %>
    </tr>
  <% end %>


  <% end %>
</table>
<% end %>

app/views/users/_user.html.erb
    <li>
      <%= gravatar_for user%>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
          data: { confirm: "You sure?"} %>
      <% end %>
    </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>


<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
       <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
  